### ISSUE TITLE
Twitter plugin exceptions in OctoberCMS build 337

### ISSUE THREAD

**Issue by hybridvision** [rainlab/twitter-plugin#10]
After updating a project that was using the Twitter plugin, I get the following error on the front end:

`Class 'HTML' not found`

![image](https://cloud.githubusercontent.com/assets/11492432/15549234/fa8ca0e0-22ab-11e6-98e7-8836da9882b1.png)

I also get this error in the CMS when trying to inspect the component:

`"The component 'RainLab\Twitter\Components\EmbedTimeline' does not contain a method 'getLangOptions'." on line 278 of /home/vagrant/sites/test/www/modules/cms/Classes/ComponentBase.php`

![image](https://cloud.githubusercontent.com/assets/11492432/15549417/b56199fc-22ac-11e6-8bfc-3ec2ac64afb9.png)

I have build 337 of OctoberCMS and version 1.0.3 of the Twitter plugin. Everything is up to date according to the dashboard.

I haven't been able to find yet where the mysterious HTML class went but I assume the code was refactored and this wasn't updated yet. For the getLangOptions error, is that related to the recent multi-lingual updates that have been done?

I know this is a relatively simple plugin and it would be great if someone has a quick fix. Unfortunately I don't have much time right now to look into it with a deadline looming...

Thanks!

**Comment by daftspunk** [comment]
Try it again with latest code base

**Comment by hybridvision** [comment]
Wow, that was quick! Works like a charm! 👍 

Many thanks, Samuel!
