### ISSUE TITLE
Two Exceptions Occuring with EmbedTimeline component

### ISSUE THREAD

**Issue by billyzduke** [rainlab/twitter-plugin#11]
In Components\EmbedTimeline.php...

1) Line 113, function getLangOptions() needs to be public, not protected.

2) Lines 4 & 152, OctoberCMS case-sensitive alias for October\Rain\Support\Facades\Html class is "Html", not "HTML".

**Comment by daftspunk** [comment]
Latest code shows these changes are already done.

https://github.com/rainlab/twitter-plugin/blob/master/components/EmbedTimeline.php
