### ISSUE TITLE
Twitter Has Changed Their Widget Generation Process - Can No Longer Find Widget ID

### ISSUE THREAD

**Issue by billyzduke** [rainlab/twitter-plugin#13]
Not really your issue per se, though Twitter's recent updates do somewhat kneecap your component functionality. An embedded timeline I set up on a site a little over a week ago (when I could still get the Widget ID) is still functioning, but can't really move forward with no way to acquire that ID for a new embedded timeline...

**Comment by daftspunk** [comment]
Need to find the updated instructions...

**Comment by wvelez6** [comment]
Under Twitter Settings click on Widgets, click on edit on the widget you want. In that page you should see an html embed code and there you will see  data-widget-id="123456789876543212">, copy the number and place under the WidgetID of the Twitter plugin.

**Comment by billyzduke** [comment]
It doesn't work that way anymore on twitter.com.  If I click on Widgets, there are never any widgets listed, so I must click Create New button. This takes me to publish.twitter.com, which is the new generation process I did not see when I did this previously. There, I can choose to make an embedded timeline widget, but this is the embed code it now gives me, which contains no id:

`<a class="twitter-timeline" href="https://twitter.com/billyzduke">Tweets by Billy Z Duke</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

**Comment by daftspunk** [comment]
This relates to the `EmbedTimeline` component.

@billyzduke, so it would appear the logic is more magical and doesn't need a widget ID or anything. It can figure out the widget type and account from the anchor link given before the script tag. 

This plugin will require some changes to fix this. More specifically it needs to be simplified to only ask for the username.

I have assigned this to myself so I don't forget about it, but someone else feel free to make these changes and submit a Pull Request.

**Comment by tashavanes** [comment]
Hi all, am new here, is there any ETA for this commit to be available as 1.0.6? Can't get twitter working as I'd like with 1.0.5.

**Comment by bnordland** [comment]
@daftspunk do you have any thoughts on the pull request I submitted?

**Comment by LukeTowers** [comment]
@bnordland I submitted a review to your PR but you never responded.
Closing as it has been over a month since any activity on this occurred.
