### ISSUE TITLE
Error when setting component params

### ISSUE THREAD

**Issue by mitjarobic** [rainlab/twitter-plugin#15]
"The component 'RainLab\Twitter\Components\FollowButton' does not contain a method 'getLangOptions'." on line 278 of /var/www/modules/cms/classes/ComponentBase.php

Build 384

**Comment by daftspunk** [comment]
Fixed in v1.0.5

**Comment by mitjarobic** [comment]
The plugin version is still 1.0.4

https://octobercms.com/plugin/rainlab-twitterfeed#changelog

**Comment by daftspunk** [comment]
Sorry that should be fixed now.
