### ISSUE TITLE
Hashtags not displaying when using "Latest tweet" component

### ISSUE THREAD

**Issue by tashavanes** [rainlab/twitter-plugin#17]
1.0.5 
Instead of embed, I am currently trying the "latest tweet" component. Is displaying my tweets ok, except it appears to be escaping hashtags. 

Ex (blanks here are 2 hashtags): 
![screen shot 2017-01-09 at 6 10 20 am](https://cloud.githubusercontent.com/assets/13317762/21764679/5ab5c94e-d632-11e6-99dc-f1331c56a42d.png)

snippet in use
`{% component 'latestTweet' %}`

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
