### ISSUE TITLE
Unable to display a single tweet

### ISSUE THREAD

**Issue by jonpxpx** [rainlab/twitter-plugin#4]
Due to values being switched to boolean if 1 or 0, tweet-limit doesn't allow you to set it to 1 and therefore returns all.

This isn't the most elegant way of fixing this, but I added

```
if($key != 'tweet-limit')
```

within

```
switch ($value) {
        case '1':
                if($key != 'tweet-limit')
                $value = 'true';
            break;
        case '0':
            $value = 'false';
            break;
        default:
            $value = $value;
            break;
}
```

To fix the issue.

**Comment by daftspunk** [comment]
Can you submit this as a PR?

**Comment by jonpxpx** [comment]
Never had to do one, but I will give it a go :)

**Comment by jonpxpx** [comment]
@daftspunk can you push an updated package to octobercms.com please? Not updating via the backend at the moment...
