### ISSUE TITLE
Twitter plugin fails when cache set to database

### ISSUE THREAD

**Issue by jamiegrand** [rainlab/twitter-plugin#9]
Once you set the following config the plugin no longer works.

` /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache connection that gets used while
    | using this caching library. This connection is used when another is
    | not explicitly specified when executing a given caching function.
    |
    */

```
'default' => 'database',`
```

**Comment by daftspunk** [comment]
More info needed here, any errors?

**Comment by jamiegrand** [comment]
sorry stopped using the plugin a while back because of this , If i remember rightly I was getting an occasional memory / unserilize fault which was crashing the site , which switching to database solved but rendered the plugin useless in the partial , no errors just didnt work.

Will go back to it at some point but the site is ever growing... http://welldoing.org/

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.
